/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface NodecgToggle {
    'color': string;
    'disabled': boolean;
    'label': string;
  }
}

declare global {


  interface HTMLNodecgToggleElement extends Components.NodecgToggle, HTMLStencilElement {}
  var HTMLNodecgToggleElement: {
    prototype: HTMLNodecgToggleElement;
    new (): HTMLNodecgToggleElement;
  };
  interface HTMLElementTagNameMap {
    'nodecg-toggle': HTMLNodecgToggleElement;
  }
}

declare namespace LocalJSX {
  interface NodecgToggle extends JSXBase.HTMLAttributes<HTMLNodecgToggleElement> {
    'color'?: string;
    'disabled'?: boolean;
    'label'?: string;
  }

  interface IntrinsicElements {
    'nodecg-toggle': NodecgToggle;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


